// Code generated by the Lingua Franca compiler from:
// file://home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/jk/Documents/vehicles/controllers/boomer/src-gen/lfc-src/webotsClient"
#include "include/ctarget/ctarget.h"
#include "core/threaded/reactor_threaded.c"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
#include <stdio.h>
#include <string.h>
#include <webots/camera.h>
#include <webots/gps.h>
#include <webots/keyboard.h>
#include <webots/led.h>
#include <webots/lidar.h>
#include <webots/motor.h>
#include <webots/robot.h>

// to be used as array indices
enum { X, Y, Z };

// This needs to be changed if the .wbt model changes
#define FRONT_WHEEL_RADIUS 0.38
#define REAR_WHEEL_RADIUS 0.6

// devices
WbDeviceTag left_steer, right_steer;
WbDeviceTag left_front_wheel, right_front_wheel;
WbDeviceTag left_rear_wheel, right_rear_wheel;

// lights
WbDeviceTag left_flasher, right_flasher, tail_lights;
WbDeviceTag work_head_lights, road_head_lights;

// camera
WbDeviceTag camera;
int camera_width = -1;
int camera_height = -1;
double camera_fov = -1.0;

// SICK laser
WbDeviceTag sick;
int sick_width = -1;
double sick_range = -1.0;
double sick_fov = -1.0;

// GPS
WbDeviceTag gps;
double gps_coords[3];
double gps_speed = 0.0;

// misc variables
int time_step = -1;
double speed = 0.0;
double steering_angle = 0.0;
double manual_steering = 0.0;

void blink_lights() {
int on = (int)wb_robot_get_time() % 2;
wb_led_set(left_flasher, on);
wb_led_set(right_flasher, on);
wb_led_set(tail_lights, on);
wb_led_set(work_head_lights, on);
wb_led_set(road_head_lights, on);
}

void print_help() {
printf("You can drive this vehicle!\n");
printf("Select the 3D window and then use the cursor keys to:\n");
printf("[LEFT]/[RIGHT] - steer\n");
printf("[UP]/[DOWN] - accelerate/slow down\n");
}

// set target speed
void set_speed(double kmh) {
if (kmh > 30.0)
    kmh = 30.0;

speed = kmh;

printf("setting speed to %g km/h\n", kmh);

double front_ang_vel = kmh * 1000.0 / 3600.0 / FRONT_WHEEL_RADIUS;
double rear_ang_vel = kmh * 1000.0 / 3600.0 / REAR_WHEEL_RADIUS;

// set motor rotation speed
wb_motor_set_velocity(left_front_wheel, front_ang_vel);
wb_motor_set_velocity(right_front_wheel, front_ang_vel);
wb_motor_set_velocity(left_rear_wheel, rear_ang_vel);
wb_motor_set_velocity(right_rear_wheel, rear_ang_vel);
}

// positive: turn right, negative: turn left
void set_steering_angle(double wheel_angle) {
steering_angle = wheel_angle;
wb_motor_set_position(left_steer, steering_angle);
wb_motor_set_position(right_steer, steering_angle);
}

void change_manual_steer_angle(double inc) {
double new_manual_steering = manual_steering + inc;
printf("steer %f\n", new_manual_steering);
if (new_manual_steering <= 0.94 && new_manual_steering >= -0.94) {
    manual_steering = new_manual_steering;
    set_steering_angle(manual_steering);
}

if (manual_steering == 0)
    printf("going straight\n");
else
    printf("turning %.2f rad (%s)\n", steering_angle, steering_angle < 0 ? "left" : "right");
}

void check_keyboard() {
int key = wb_keyboard_get_key();
switch (key) {
    case WB_KEYBOARD_UP:
    set_speed(speed + 1.0);
    break;
    case WB_KEYBOARD_DOWN:
    set_speed(speed - 1.0);
    break;
    case ' ':
    set_speed(0.0);
    break;
    case WB_KEYBOARD_RIGHT:
    change_manual_steer_angle(+0.02);
    break;
    case WB_KEYBOARD_LEFT:
    change_manual_steer_angle(-0.02);
    break;
}
}
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class webotsClient
typedef struct {
    struct self_base_t base;
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    reaction_t _lf__reaction_0;
    trigger_t _lf__startup;
    reaction_t* _lf__startup_reactions[1];
} webotsclient_self_t;
// ***** Start of method declarations.
// ***** End of method declarations.
#include "include/ctarget/set.h"
void webotsclientreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    webotsclient_self_t* self = (webotsclient_self_t*)instance_args;
    #pragma GCC diagnostic pop
    #line 135 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    wb_robot_init();
    time_step = (int)wb_robot_get_basic_time_step();
    
    // find wheels
    left_front_wheel = wb_robot_get_device("left_front_wheel");
    right_front_wheel = wb_robot_get_device("right_front_wheel");
    left_rear_wheel = wb_robot_get_device("left_rear_wheel");
    right_rear_wheel = wb_robot_get_device("right_rear_wheel");
    wb_motor_set_position(left_front_wheel, INFINITY);
    wb_motor_set_position(right_front_wheel, INFINITY);
    wb_motor_set_position(left_rear_wheel, INFINITY);
    wb_motor_set_position(right_rear_wheel, INFINITY);
    
    // get steering motors
    left_steer = wb_robot_get_device("left_steer");
    right_steer = wb_robot_get_device("right_steer");
    
    // camera device
    camera = wb_robot_get_device("camera");
    wb_camera_enable(camera, time_step);
    camera_width = wb_camera_get_width(camera);
    camera_height = wb_camera_get_height(camera);
    camera_fov = wb_camera_get_fov(camera);
    
    // SICK sensor
    sick = wb_robot_get_device("Sick LMS 291");
    wb_lidar_enable(sick, time_step);
    sick_width = wb_lidar_get_horizontal_resolution(sick);
    sick_range = wb_lidar_get_max_range(sick);
    sick_fov = wb_lidar_get_fov(sick);
    
    // initialize gps
    gps = wb_robot_get_device("gps");
    wb_gps_enable(gps, time_step);
    
    // find lights
    left_flasher = wb_robot_get_device("left_flasher");
    right_flasher = wb_robot_get_device("right_flasher");
    tail_lights = wb_robot_get_device("tail_lights");
    work_head_lights = wb_robot_get_device("work_head_lights");
    road_head_lights = wb_robot_get_device("road_head_lights");
    
    // start engine
    set_speed(15);  // km/h
    
    print_help();
    
    // allow to switch to manual control
    wb_keyboard_enable(time_step);
    
    // main loop
    while (wb_robot_step(time_step) != -1) {
    // get user input
    check_keyboard();
    
    // read sensors
    const unsigned char *camera_image = wb_camera_get_image(camera);
    // const float *sick_data = wb_lidar_get_range_image(sick);
    
    // update stuff
    blink_lights();
    }
    
    wb_robot_cleanup();
        
}
#include "include/ctarget/set_undef.h"
webotsclient_self_t* new_webotsClient() {
    webotsclient_self_t* self = (webotsclient_self_t*)_lf_new_reactor(sizeof(webotsclient_self_t));
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    self->_lf__reaction_0.number = 0;
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    self->_lf__reaction_0.function = webotsclientreaction_function_0;
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    self->_lf__reaction_0.self = self;
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    self->_lf__reaction_0.STP_handler = NULL;
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    self->_lf__reaction_0.name = "?";
    #line 134 "file:/home/jk/Documents/vehicles/controllers/boomer/lfc-src/webotsClient.lf"
    self->_lf__reaction_0.mode = NULL;
    self->_lf__startup_reactions[0] = &self->_lf__reaction_0;
    self->_lf__startup.last = NULL;
    self->_lf__startup.reactions = &self->_lf__startup_reactions[0];
    self->_lf__startup.number_of_reactions = 1;
    self->_lf__startup.is_timer = false;
    return self;
}
// =============== END reactor class webotsClient
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t** _lf_timer_triggers = NULL;
int _lf_timer_triggers_size = 0;
// Array of pointers to startup triggers.
reaction_t* _lf_startup_reactions[1];
int _lf_startup_reactions_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
// Array of pointers to reset triggers.
reaction_t** _lf_reset_reactions = NULL;
int _lf_reset_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_reset_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    webotsclient_self_t* webotsclient_self[1];
    // ***** Start initializing webotsClient of class webotsClient
    webotsclient_self[0] = new_webotsClient();
    int bank_index = 0;
    _lf_startup_reactions[_lf_startup_reactions_count++] = &webotsclient_self[0]->_lf__reaction_0;
    webotsclient_self[0]->_lf__reaction_0.deadline = NEVER;
    //***** End initializing webotsClient
    // **** Start deferred initialize for webotsClient
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of webotsClient.
        webotsclient_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0;
        }
        
        // ** End initialization for reaction 0 of webotsClient
    }
    // **** End of deferred initialize for webotsClient
    // **** Start non-nested deferred initialize for webotsClient
    // **** End of non-nested deferred initialize for webotsClient
    // Connect inputs and outputs for reactor webotsClient.
    // Set reaction priorities for ReactorInstance webotsClient
    {
        webotsclient_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        webotsclient_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[1] = 
        {1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 1};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
}
void _lf_trigger_startup_reactions() {
    for (int i = 0; i < _lf_startup_reactions_size; i++) {
        if (_lf_startup_reactions[i] != NULL) {
            _lf_trigger_reaction(_lf_startup_reactions[i], -1);
        }
    }
}
void _lf_initialize_timers() {

}
void logical_tag_complete(tag_t tag_to_send) {

}
bool _lf_trigger_shutdown_reactions() {
    return false;
}
void terminate_execution() {}
